### ISSUE TITLE
ERROR! 'warn' is not a valid attribute for a Task

### ISSUE THREAD

**Issue by leonsp** [juju4/ansible-redhat-epel#1]
I'm trying to use the falco role that depends on this role, and I'm getting this error:
```
ERROR! 'warn' is not a valid attribute for a Task

The error appears to have been in '/foo/ansible/roles/juju4.redhat-epel/tasks/redhat-epel.yml': line 19, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

## FIXME! ansible not detecting package already installed if http
- name: check if epel installed
  ^ here

This error can be suppressed as a warning using the "invalid_task_attribute_failed" configuration
```

I'm using Ansible 2.7.0:
```
$ ansible-playbook --version
ansible-playbook 2.7.0
  config file = /foo/ansible.cfg
  configured module search path = ['/bar/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.7.0 (default, Oct  2 2018, 09:20:07) [Clang 10.0.0 (clang-1000.11.45.2)]
```

**Comment by andrewhowdencom** [comment]
This has been fixed upstream, but is not yet tagged. Ansible galaxy will (if i remember correctly) resolve only stable versions, not commits on master.

Tagging it should fix this issue.

**Comment by juju4** [comment]
It does not seem to be the case
https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html
> The version of the role to download. Provide a release tag value, commit hash, or branch name. Defaults to master.

but anyway doing a new tag is on my list after long linting work...

Please confirm as I don't use that much galaxy to install role as IMHO, it misses the critical update option.

**Comment by andrewhowdencom** [comment]
Hmm. That is also how I read the docs, but running the following:

```
$ cd $(mktemp -d)
$ ansible-galaxy install juju4.redhat_epel
- downloading role 'redhat_epel', owned by juju4
- downloading role from https://github.com/juju4/ansible-redhat-epel/archive/v0.8.tar.gz
- extracting juju4.redhat_epel to /home/andrewhowden/.ansible/roles/juju4.redhat_epel
- juju4.redhat_epel (v0.8) was installed successfully
```

Yeilded the `0.8` version last tagged. You can then adjust it with:

```
$ ansible-galaxy install juju4.redhat_epel,master --force
- changing role juju4.redhat_epel from v0.8 to master
- downloading role 'redhat_epel', owned by juju4
- downloading role from https://github.com/juju4/ansible-redhat-epel/archive/master.tar.gz
- extracting juju4.redhat_epel to /home/andrewhowden/.ansible/roles/juju4.redhat_epel
- juju4.redhat_epel (master) was installed successfully
```

But it looks like it defaults to a tag. I think the relevant docs are here:

https://galaxy.ansible.com/docs/contributing/version.html

> Galaxy imports content from repositories on GitHub, and as part of the import process, it scans the repository’s git tags, looking for any that match the Semantic Version format. Tags that match the format are considered to be versions and imported, and those that don’t are skipped.

But I haven't looked extensively.

**Comment by juju4** [comment]
They are kind of contradicting themselves. Galaxy lint says ignoring non-semantic versioning. so v0.8 should be ignored...
Anyway, new tag coming, just want to finish some housekeeping on my many roles.

Thanks for the feedback!

**Comment by juju4** [comment]
new tag added. issue should be solved. comment if not.

**Comment by andrewhowdencom** [comment]
In a bout of stunning ansible consistency, `v0.8` is ranked higher than `0.9.0`. 

```
$ ansible-galaxy install juju4.redhat_epel --force
- changing role juju4.redhat_epel from 0.9.0 to unspecified
- downloading role 'redhat_epel', owned by juju4
- downloading role from https://github.com/juju4/ansible-redhat-epel/archive/v0.8.tar.gz
- extracting juju4.redhat_epel to /home/andrewhowden/.ansible/roles/juju4.redhat_epel
- juju4.redhat_epel (v0.8) was installed successfully
```

You can stlil specify the version manually so it is correct.

Depending on how muchc it bothers you, I think you're going ot have to:

- Additionally start tags with `v${TAG}`
- Delete old `v${TAG}` 

The latter is going to break shit.

I would recommend noting the issue on the README and signalling that you'll remove tags in ~12 months or so. It'll still break stuff, but 12 months is a reasonable amount of time for people to rediscover this problem with Ansible and bump the versions manually.

**Comment by juju4** [comment]
WTF...
Galaxy says semantic versioning. https://galaxy.ansible.com/docs/contributing/version.html

I think an issue upstream is better. https://github.com/ansible/galaxy/
will look at it
